# config.yaml
log_level: INFO
log_dir: logs

default_alpha: 0.1
default_blend_mode: linear
default_demucs_model: htdemucs_ft
default_mode: default
supported_extensions: wav, mp3, flac
default_smooth_factor: 1.0
max_threads: 4
output_base: processed
enable_evaluation: False